dirvish-mon: convert to perl, show last line of log.tmp instead of parsing lsof for active files

diff --git a/sbin/dirvish-mon b/sbin/dirvish-mon
--- a/sbin/dirvish-mon
+++ b/sbin/dirvish-mon
@@ -1,108 +1,290 @@
-#! /bin/bash
+#!/usr/bin/perl
+#
+# Dirvish-mon - monitor Dirvish jobs
+#
+use strict;
+use warnings;
+use Getopt::Long qw(GetOptionsFromArray :config gnu_compat permute bundling);
+use Fcntl;
+use POSIX qw(strftime);
+use File::ReadBackwards;
+use JobTools::Utils qw(:Opt CompressByteSize);
 
-function Space {
+# Initialize variables.
+my $Prog=$0;			# Get our name, for messages.
+$Prog=~s/\.pl$|\.bat$//;	# Trim off the suffix, if present.
+$Prog=~s".*[/\\]"";		# Trim off the path, if present.
+$ENV{PATH} = '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin';
+my @Args=@ARGV;			# Preserve orig command for ref.
+my $ErrorFlag=0;		# No errors so far.
+my @ConfigFiles=("/usr/local/etc/${Prog}.cfg");     # Name of config files.
+our $Errors=0;
+our %Config;
+our @Parms;
+our %Options;			# Options settings.
+JobTools::Utils::init(config => \%Config, options => \%Options);
 
+# Define our command-line options.  I use sub for everything, because
+# GetOptions doesn't work right on a second call to it (which we need
+# to do) with the conventional approach.
+$DB::AutoTrace=$DB::AutoTrace;		# Suppress spurious warning.
+my %OptionSpecifications;
+%OptionSpecifications=(
+	'<>'			=>	sub {my $Arg = shift; push @Parms,$Arg if (length($Arg));},
+#	'always-mail|m=s'	=>	\&OptArray,
+#	'always-page|p=s'	=>	\&OptArray,
+#	'debug|d'		=>	sub {$DB::AutoTrace=1;},
+#	'error-mail|M=s'	=>	\&OptArray,
+#	'error-page|P=s'	=>	\&OptArray,
+#	'filter-file|F=s'	=>	\&OptArray,
+	'count=n'		=>	\&OptValue,
+	'help|h|?!'		=>	\&opt_h,
+	'html!'			=>	\&OptFlag,
+	'interval=n'		=>	\&OptValue,
+	'option-set|O=s'	=>	sub {OptOptionSet(name => $_[1],optspec => \%OptionSpecifications);},
+#	'remote|R=s'		=>	sub {OptArray(@_,'allow-delete'=>1,'expand-config'=>1);},
+	'test|t'		=>	\&OptFlag,
+	'verbose|v'		=>	\&OptFlag,
+);
+our $ExitCode;
+
+# ---------------------------------------------------------
+#
+# Process the command line options.
+#
+%Options=(verbose => 0);        # Initialize Options.
+die "Invalid options specified\n" unless (GetOptions(%OptionSpecifications));
+$Options{interval} = 30 unless ($Options{interval} and $Options{interval} =~ /^[1-9]\d+/);
+
+# ---------------------------------------------------------
+#
+# Verify the command line and run the job.
+#
+die('Excess parameters on the command line: "' . join(' ',@Parms) . "\" See \"$Prog -h\" for usage.")
+	if (@Parms);
+
+
+# ---------------------------------------------------------
+#
+# Gather and display the data in a loop.
+#
+
+while ( ! exists($Options{count}) or ($Options{count} > 0)) {
+	my $StartTime = time();
+	RunCycle();
+	if (exists($Options{count})) {
+		$Options{count}--;
+		last if ($Options{count} < 1);
+	}
+	my $SleepTime = $Options{interval} - (time() - $StartTime);
+	sleep($SleepTime);
+}
+
+exit(0);
+
+
+sub RunCycle {
+
+	my %LogFiles;
+	my $LSOF;
+	my $VaultMax = 0;	# Length of longest vault name.
+	if (open($LSOF,'lsof -c rsync -b 2> /dev/null |')) {
+		while (<$LSOF>) {
+			chomp;
+			print "Verbose: lsof returned: $_\n" if ($Options{verbose}>=3);
+			# rsync   3218 root    1w   REG              252,0     22510 36964139 /usr/local/dirvish/vinnie/2017-05-24-Wed-test/log.tmp
+			next unless (m"^rsync\s+(\d+)\s+\S+\s+\S+\s+REG\s+\S+\s+\d+\s+\d+\s+(\S*/log.tmp)\s*$");
+			my ($pid,$logfile) = ($1,$2);
+			print "Verbose: Found PID $pid and logfile $logfile\n" if ($Options{verbose}>=2);
+			next if (exists($LogFiles{$logfile}));		# Have already seen this file.
+			$LogFiles{$logfile}->{pid} = $pid;		# Save the PID
+			my $vault = $logfile;
+			$vault =~ s"/log.tmp$"";			# Extract the vault path.
+			$LogFiles{$logfile}->{vaultpath} = $vault;	# Save the vault path.
+			$vault =~ s"^.*/(\S+)/\S+$"$1";			# Extract just the vault name.
+			$LogFiles{$logfile}->{vault} = $vault;		# Save the vault name.
+			$VaultMax = length($vault) if (length($vault) > $VaultMax);
+			my $space = `df -hlP "$LogFiles{$logfile}->{vaultpath}" | grep -v ^Filesystem`;
+			$space =~ s/^\S+\s+\S+\s+\S+\s+\S+\s+(\S+)\s//;
+			$LogFiles{$logfile}->{percentfull} = $1;
+		}
+		close $LSOF;
+	}
 	
-	filename="$1"
-#	Filesystem      Size  Used Avail Use% Mounted on
-#	/dev/md2         46G  9.8G   34G  23% /
-	data=`df -hlP "${filename%/*}" 2> /dev/null | awk '!/Filesystem/ {print \$4, \$5;}'`
-	avail=${data%% *}
-	percent=${data##* }
-	percent=${percent%%}
-	echo "$percent($avail free)"
+	foreach my $logfile (keys(%LogFiles)) {
+		my $LOGFH = File::ReadBackwards->new( $logfile ) or next;
+		until ($LOGFH->eof) {
+			my $line = $LOGFH->readline;
+			next unless ($line =~ /^[c>h.]([fdLDS])\S+\s+(.*?)\s*$/);
+			$LogFiles{$logfile}->{type} = $1;
+			$LogFiles{$logfile}->{lastfile} = $2;
+			last;
+		}
+		$LOGFH->close;
+		my $mtime = (stat($logfile))[9];
+		$LogFiles{$logfile}->{mtime} = 
+			POSIX::strftime('%T',localtime($mtime));
+		if ($LogFiles{$logfile}->{lastfile}
+			and ($LogFiles{$logfile}->{type} eq 'f')
+		) {
+			my $lastfile = $LogFiles{$logfile}->{vaultpath} . "/tree/" . $LogFiles{$logfile}->{lastfile};
+			my $size = (stat($lastfile))[7];
+			$LogFiles{$logfile}->{size} = CompressByteSize($size);
+			#print "debug: size=$size\n";
+		}
+		else {
+			$LogFiles{$logfile}->{size} = $LogFiles{$logfile}->{type};
+		}
+	}
+	
+	if (keys(%LogFiles) == 0) {
+		print "No rsync processes running.\n";
+	}
+	else {
+		foreach my $logfile (sort(keys(%LogFiles))) {
+			printf "%-8s %5d % 4s % 6s %-*s: %s\n",
+				$LogFiles{$logfile}->{mtime},
+				$LogFiles{$logfile}->{pid},
+				$LogFiles{$logfile}->{percentfull},
+				$LogFiles{$logfile}->{size},
+				$VaultMax,
+				$LogFiles{$logfile}->{vault},
+				$LogFiles{$logfile}->{lastfile},
+			;
+		}
+		
+	}
 }
 
-function ReadLSOF {
-	grep tree/ |
-	head -n 1 | 
-	while read trash pid trash fh type trash item7 item8 rest
-	do
-		if [[ "$type" = "unknown" ]]
-		then
-			filename="$item7 item8 rest"
-		else
-			filename="${rest# *}"
-			filename="${filename# *}"
-		fi
-		# [[ $fh = [0-9]*r ]] && continue			# Filter out input file.
-		filename="${filename% (*}"			# Clean up NFS mounts.
 
-		space=`Space $filename`
-
-		# Get size in a compact unit.
-		size=`stat -c %s "$filename" 2> /dev/null`
-		if [[ -z "$size" ]]
-		then
-			size='  ?'
-		elif [[ size -gt 1024**4 ]]
-		then
-			size=`printf "%'dT" $(($size/1024**4))`
-		elif [[ size -gt 1024**3 ]]
-		then
-			size=`printf "%'dG" $(($size/1024**3))`
-		elif [[ size -gt 1024**2 ]]
-		then
-			size=`printf "%'dM" $(($size/1024**2))`
-		elif [[ $size -gt 1024 ]]
-		then
-			size=`printf "%dK" $(($size/1024))`
-		else
-			size="${size}B"
-		fi
-
-		filename=`echo "$filename" | sed 's/^.*\/\(.*\/.*\/tree\)/\1/'`		# Strip down to vault.
-		printf "%-s %5d %-6s %13s %4s: %s\n" $now $pid "rsync" "$space" $size "$filename"
-	done 
+# ---------------------------------------------------------
+#
+# Wrap up.
+#
+if ($ExitCode) {
+	warn "$Prog failed.\n";
+} else {
+	#print "$Prog ended normally.\n";
 }
 
-Once=$1
-while ps -ef | grep dirvish | grep -qv grep
-do
-	now=`date +%T`
+$ExitCode=$Errors?10:0;
+exit($ExitCode);
 
-	# Report on rsync's in progress
-	ps -ef |
-	grep rsync |
-	grep -v grep |
-	while read trash pid trash
-	do
-		lsof -p $pid |
-			ReadLSOF
-	done |
-	sort
 
-	# Report on dirvish-expire in progress
-	prior=''
-	ps -ef | 
-	grep dirvish-expire |
-	grep -v grep |
-	while read trash pid trash
-	do
-		line=`pstree -p $pid`
-		line=${line##*--rm(}
-		line=${line%%)*}
-		[[ $line =~ /^[0-9]+$/ ]] || continue
-		[[ -n $line ]] && lsof -p $line | 
-			grep ' [0-9]r  *DIR '
-	done |
-	while read trash pid trash trash trash trash trash trash dir
-	do
-		dir=${dir%%/tree/*}
-		space=`Space $filename`
-		printf "%-s %5d %-6s %13s     : %s\n" $now $pid "expire" "$space" "$dir"
-	done |
-	sort -r |
-	while read current
-	do
-		if [[ -z "$prior" || "$prior" != $current* ]]
-		then
-			echo "$current"
-		fi
-		prior=$current
-	done
-	[[ "$Once" = "1" ]] && exit
-	sleep 30
-done
-date '+No dirvish processes running at %T'
+# ---------------------------------------------------------
+#
+# opt_h: Usage
+#
+sub opt_h {
 
+	use FindBin qw($RealBin $RealScript);
+
+	system(qq<pod2text $RealBin/$RealScript | sed "s/%Prog/$Prog/g" | more>);
+exit 1;
+}
+
+=pod
+
+=head1 %Prog -  
+
+=head3 Usage:  
+        %Prog [flag1 ...]
+
+        %Prog -h
+
+=head3 Options:
+        --always-mail|-m addr:  Mailid: Send an execution report to
+                                this e-mail address.
+        --always-page|-p addr:  Page: Send a very brief message
+                                (suitable for a pager) to this e-mail
+                                address when this job completes.
+        --error-mail|-e mailid: Error: Send an execution report to this
+                                e-mail address if errors are detected.
+        --error-page|-P addr:   Page error: Send a very brief message to
+                                this e-mail address if errors are
+                                detected in this job.
+        --filter|-F filter:     Filter: Use alternate error detection
+                                filter file "filter".  The default is
+                                to use the built-in error filter.
+        --option-set|-O config: Insert the "config" configuration options
+                                from /usr/local/etc/%Prog.cfg
+                                into the command line at this point.
+	--remote-host|-R host	Remote: Run this on one or more remote
+				hosts.  "host" may be a host name, an
+				IP address, a configuration file entry
+				name, or a comma or space separated list of
+				any mix of these.  This option may also be
+				repeated to append to the list.  Host names
+				preceeded by ! are removed from the list.
+				This is primarily to allow a configuration
+				file list to be included, but some of the
+				hosts in the list to subsequently be excluded.
+        --test|-t:              Test: echo commands instead of running them.
+        --verbose|-v:           Verbose: echo commands before running them.
+				May be used multiple times to increase verbosity.
+        --help|-h:              Help: display this panel
+
+=head3 Parameters:
+        (none)
+
+=head3 Configuration files
+
+Configuration data may be loaded from the configuration files.  These files
+form key-value pairs that $Prog may reference.  The syntax of the file is:
+
+        name: value
+
+"name" must begin in column 1, and is case-insensitive.  Lines beginning
+with white-space are treated as continuations of the previous line.  Blank
+lines or lines beginning with # are ignored.
+
+Several "names" are reserved, as follows:
+
+=over
+
+=item *
+Alljobs: any value listed here is prepended to the command line before
+command line processing begins.  This permits default options to be
+set.
+
+=item *
+Defaultjob: any value listed here is used as the command line if no
+command line options are specified.
+
+=item *
+Include: any value here is treated as another configuration file, which
+is loaded immediately.
+
+=back
+
+=head3 Return codes:
+        0       :       Normal termination
+        1       :       Help panel displayed.
+        2       :       Invalid or unrecognized command line options.
+        3       :       Invalid or unrecognized command line option value.
+        4       :       Incorrect command line parameters.
+        5       :       Unexpected message found in output.
+
+
+=head3 Notes:
+
+=cut
+
+__END__
+#
+# ---------------------------------------------------------
+# See LogOutput.pm for an explanation of output filtering.
+IGNORE	"^\s*(\S+:\s*)?$"
+IGNORE	"^\s*(\S+:\s*)?\S+:\s+Starting \S+ at \d+:\d+:\d+ on \S+, \d\d\d\d-\d\d-\d\d...\s*$"
+IGNORE	"^\s*\S+:\s*\S+ ended normally with status 0 and signal 0"
+IGNORE	"^\s*\S+:\s*\S+ ended on \S+, \d\d\d\d-\d\d-\d\d at \d\d:\d\d:\d\d"
+IGNORE	"^\s*\S+:\s*\S+:\s+\S+ ended normally with status 0 and signal 0"
+IGNORE	"^\s*\S+:\s+\S+ started on \S+ on \S+, \d+-\d+-\d+ at \d+:\d+:\d+"
+IGNORE	"^\s*\S+:\s+Command: "
+LOGONLY "^\s*\S+ started on \S+ on \S+, \d+-\d+-\d+ at \d+:\d+:\d+"
+LOGONLY "^\s*Command: "
+SHOW	"^\s*(\S+:\s*)?(Test|Executing|Verbose|debug):"
+SHOW	"^\s*(\S+:\s*)?Starting \S+ at \d+:\d+:\d+ on \S+, \d\d\d\d-\d\d-\d\d...\s*$"
+SHOW	"^\s*\S+ ended normally with status 0 and signal 0$"
+SHOW	"^\s*\S+ ended on \S+, \d\d\d\d-\d\d-\d\d at \d\d:\d\d:\d\d"
+SHOW	"^\s*\S+:\s*Remote job ended at ..:..:.., return code =   0, signal =   0, run time = "
